server:
  context-path: /springboot-test1
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/woundplast
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111111
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 1000MB
  profiles:
    active: pro
mybatis:
  type-aliases-package: com.baizhi.springboot.entity
  mapper-locations: com/baizhi/springboot/dao/*Dao.xml
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  reasonable: true
  params: count=countsql
